server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka
  main:
    allow-bean-definition-overriding: true

logging:
  config: classpath:logback.xml
  smallweb:
    file: D:/logs/smallweb/eureka
    level: ERROR
    moduleName: smallweb.eureka